apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  namespace: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front-container
          image: somg0703/front:latest
          ports:
            - containerPort: 3000
              protocol: TCP
